# Site settings
title: Ember Hearth
app_name: Ember Hearth
email: kim@kimroen.com
description: > # this means to ignore newlines until "baseurl:"
  Ember Hearth is a Mac OS application for helping you more easily get started
  with Ember and its dependencies, and then beyond that provide tools and
  conveniences for working with it in your day to day.
baseurl: "/ember-hearth" # the subpath of your site, e.g. /blog/
url: "http://ember.town" # the base hostname & protocol for your site
twitter_username: embertown
github_username:  embertown

# Build settings
markdown: kramdown

# Github defaults
highlighter: pygments

# github: is also available, with this:
# https://help.github.com/articles/repository-metadata-on-github-pages/

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      minimum_system_version: "10.10"
      category: 'release'
