# http://www.appveyor.com/docs/appveyor-yml

# see http://help.appveyor.com/discussions/questions/678-gui-unit-testing-in-appveyor#comment_35251292
os: unstable

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "4.2"
    - nodejs_version: "5.0"

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Install PhantomJS
  - npm install phantomjs-prebuilt
  # Install Bower
  - npm install -g bower
  - bower install
  # Typical npm stuff.
  - npm version
  - npm install

cache:
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
