'use strict';

const Term = require('./index');

class LinuxTerm extends Term{
  buildTermLaunchArgs(scriptPath) {
    return ['/usr/bin/xterm', ['-e', `bash ${scriptPath}`]];
  }

  buildRunScript(bin, args, projectDir) {
    var scriptContent,
      suffix = '.sh';

    scriptContent = `
#!/usr/bin/env sh

# generated by ember-hearth

cd ${projectDir};
${bin} ${args.join(' ')};

echo "Press any key to close the terminal...";
read
`;

    return {
      content: scriptContent,
      suffix
    };
  }
}

module.exports = LinuxTerm;
